# Generated by Django 5.0.3 on 2024-04-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(default='', max_length=256, unique=True)),
                ('game_icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
